name: FamilyStoryADA
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
options:
  bundleIdPrefix: ada.kekeluargaan
  deploymentTarget:
    iOS: "17.0"
packages:
  TOCropViewController:
    url: https://github.com/TimOliver/TOCropViewController.git
    from: 2.7.2
targets:
  FamilyStoryADA:
    type: application
    platform: iOS
    sources: [FamilyStoryADA]
    resources: [Resources]
    info:
      path: FamilyStoryADA/Info.plist
      properties:
        NSPhotoLibraryUsageDescription: "Izinkan untuk menyimpan gambar"
        NSCameraUsageDescription: "Nyalakan kamera untuk mengambil gambar"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    dependencies:
      - package: TOCropViewController
        products:
          - CropViewController
          - TOCropViewController
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ada.kekeluargaan.FamilyStoryADA
      INFOPLIST_FILE: FamilyStoryADA/Info.plist
  FamilyStoryADATests:
    type: bundle.unit-test
    platform: iOS
    sources: [FamilyStoryADATests]
    dependencies:
      - target: FamilyStoryADA
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FamilyStoryADA.app/FamilyStoryADA"
        BUNDLE_LOADER: "$(TEST_HOST)"
        INFOPLIST_FILE: FamilyStoryADA/Info.plist
schemes:
  FamilyStoryADA:
    build:
      targets:
       FamilyStoryADA: all
       FamilyStoryADATests: all
    test:
      targets:
      - name: FamilyStoryADATests
      gatherCoverageData: true
