name: FamilyStoryADA
settings:
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
  DEVELOPMENT_TEAM: ${DEVELOPMENT_ID}
options:
  bundleIdPrefix: kekeluargaan
  deploymentTarget:
    iOS: "17.0"
packages:
  TOCropViewController:
    url: https://github.com/TimOliver/TOCropViewController.git
    from: 2.7.2
  generative-ai-swift:
    url: https://github.com/google-gemini/generative-ai-swift.git
    from: 0.5.6
  Lottie:
    url: https://github.com/airbnb/lottie-ios.git
    from: 4.5.0
targets:
  FamilyStoryADA:
    type: application
    platform: iOS
    sources: [FamilyStoryADA]
    resources: [Resources]
    info:
      path: FamilyStoryADA/Info.plist
      properties:
        NSPhotoLibraryUsageDescription: "Izinkan untuk menyimpan gambar"
        NSCameraUsageDescription: "Nyalakan kamera untuk mengambil gambar"
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchStoryboardName: "LaunchScreen"
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UISupportedInterfaceOrientations~ipad:
          [
            UIInterfaceOrientationPortrait,
            UIInterfaceOrientationPortraitUpsideDown,
            UIInterfaceOrientationLandscapeLeft,
            UIInterfaceOrientationLandscapeRight,
          ]
        UTExportedTypeDeclarations:
          - UTTypeConformsTo: ["com.public.data"]
            UTTypeDescription: "DraggablePage"
            UTTypeIdentifier: "kekeluargaan.FamilyStoryADA.draggablePage"
        UIAppFonts:
          - Fredoka-VariableFont_wdth,wght.ttf
    dependencies:
      - package: TOCropViewController
        products:
          - CropViewController
          - TOCropViewController
      - package: generative-ai-swift
        products:
          - GoogleGenerativeAI
      - package: Lottie
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: kekeluargaan.FamilyStoryADA
      INFOPLIST_FILE: FamilyStoryADA/Info.plist
      ENABLE_TESTABILITY: YES
  FamilyStoryADATests:
    type: bundle.unit-test
    platform: iOS
    sources: [FamilyStoryADATests]
    dependencies:
      - target: FamilyStoryADA
    info:
      path: FamilyStoryADATests/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: BNDL
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/FamilyStoryADA.app/FamilyStoryADA"
        BUNDLE_LOADER: "$(TEST_HOST)"
        ENABLE_TESTABILITY: YES
schemes:
  FamilyStoryADA:
    build:
      targets:
        FamilyStoryADA: all
        FamilyStoryADATests: all
    test:
      targets:
        - name: FamilyStoryADATests
          gatherCoverageData: true
    run:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release
